version: '3'

services:
  app:
    build: .
    environment:
        - DB_NAME=electricity_meters
        - DB_USER=root
        - DB_PASSWORD=electricity_meters
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ht"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
    volumes:
      - static:/opt/static
    command: ["sh", "entrypoint.sh"]

  postgres:
    image: postgres:10.5
    environment:
      - POSTGRES_DB=electricity_meters
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=electricity_meters
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    volumes:
      - static:/var/www/static
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  postgres_data:
  static:
