version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
        - DB_NAME=electricity_meters
        - DB_USER=root
        - DB_PASSWORD=electricity_meters
    depends_on:
      - migrations
      - postgres

    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    volumes:
      - ./:/opt

  migrations:
    build: .
    environment:
        - DB_NAME=electricity_meters
        - DB_USER=root
        - DB_PASSWORD=electricity_meters
    depends_on:
      postgres:
        condition: service_healthy
    command: ["python", "manage.py", "migrate", "--noinput"]

  postgres:
    image: postgres:10.5
    environment:
      - POSTGRES_DB=electricity_meters
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=electricity_meters
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
