# Generated by Django 4.0.3 on 2022-03-30 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_start', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('electricity_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', related_query_name='measurement', to='electricity_meters.electricitymeter')),
            ],
        ),
    ]
